pihole:
    adminPassword: ENC[AES256_GCM,data:WVTMxA/Zj3GEflVnXNXw+SOsNALa1grTJHH3VaF0N0Q=,iv:X+DG+uQk+dcFFr6wuEwLQ6Dtyhys+baFTA9PrtOIefc=,tag:qsISRr3wuMEUKTrXYUQHdg==,type:str]
    ingress:
        annotations:
            external-dns.alpha.kubernetes.io/target: ENC[AES256_GCM,data:ZWLep+rcQyYJVmIU++E=,iv:a0ovBAbm5blKQaH5h8NjRky61lrNVNSZnPB9qCo7ylA=,tag:cMjyZJUdyNrqB7IluqiYDg==,type:str]
    dnsmasq:
        staticDhcpEntries:
            - ENC[AES256_GCM,data:QPxdoq4NNpDoXg/prE/AZl6hv7IeQ/RRRwCKOAp+V7vaVieS78Jzj06XlIcpTqB7tlMIkQ==,iv:pCRzSU2nATlsUKScBpr0h5eLQl+aHa97E1mfCyv1Ags=,tag:8i0JoNOjAfTYHneb73ItkA==,type:str]
            - ENC[AES256_GCM,data:DHmCYLsrLOLIRRdMx5MoomSaBGlzv5dmifhU25X4ioFjjBfcHM/dA41uI+WTSW0=,iv:sKW/XwqQF8cv5JtuWQ9zirVi4mUgoBkfME8Y0bXqQDw=,tag:fqOUvlan0VwgET2N4quD5g==,type:str]
            - ENC[AES256_GCM,data:jgnFPQTLKmsvGpOPfNe3xXQj3ouhmbFxNNAivaESldo/8/JuajlzVNoWP4KN44TKcgW3HxTc3fc=,iv:eVOeYwOEAL57BUpZOoEc2bAkIvY07QGIVy/gDbTIUqg=,tag:DONVIvjBH7iDb0mG3KJitw==,type:str]
            - ENC[AES256_GCM,data:fgNkscVb3bFNlh5jf3JUzB5c2Q0IG/NNYfdXEKcSVdCX6STLflb+NZ8HvBGOIUYiWy7C,iv:rLppOv3UUlel5PnIWkuQC18+tLEg8GV79W3eFXt13ZA=,tag:ZU5kOr4G81z4o3yFsvZfaA==,type:str]
            - ENC[AES256_GCM,data:K2Kg8idgtT1KJxjBL92L3Bb0Z4YTJqIsNbeqFsa0dIh9kmYwllV9+dM2uU8h6yrKzyTeBVeUCKmHwLMXCz0=,iv:2yyQQZtgqSfj/DXJ8FgFsSQlkV7HjqOZr9XdHp3+JA0=,tag:9EUQo2/11+J369Lg25JdIg==,type:str]
            - ENC[AES256_GCM,data:4SyJvZr55kgiGRndx7Vn4hIxYALN+cj5Hu5MJFC3oOSl358u7BkLmIiJmTfwXdywC1s=,iv:mTkh1PqeJAX8kfcR28V7mrHY+dBBJaieblC19ulw2Lc=,tag:j4q+Sezp3RCUtmHPZhP9Kw==,type:str]
            - ENC[AES256_GCM,data:UvOV0autqOMpszaRqLJ8iVcDcJiiQPArbA5KA2Ksqv7Wpq+m6NmbQVk4+zHt2u2feXM=,iv:ilKZR0t+oRvuvkZcO9cvdqg4kHiKiDnvIt+PzBE3QhQ=,tag:Mu2RM+fOb9Jft5P50IqMLA==,type:str]
            - ENC[AES256_GCM,data:CG885RCv4xAFUmv0/EUfuOowqfLNKfEsBuhLl/UXjFgpjUHpCu5N4fpwSxICiUhUJggjl5A=,iv:DqK0s0glZwrwtZpAulox1eCwOVBNQxCLsCw7+QVCwrg=,tag:GQuWrz3VmO3NOHMmX2zrJw==,type:str]
            - ENC[AES256_GCM,data:SOatq4I6dbFZgxo8FUFSnXiFSNukFrRWZo8aqF93D2QIyblp5zU4VUSoL3EYmolv3eC65FLRz6TU,iv:OcRFuE2/Qm9ei4nZhjWQD6F1lJZxeB0rXOWqlL7Pygw=,tag:e+8OX0U5HMYRN+/NlgLL2w==,type:str]
            - ENC[AES256_GCM,data:I4hqg+xFV9yYJJfQMHSpinSqfZ6xaoOZGWZub/1ZZj7Zy/ylrzkeK4nwcvM7B0nqKOqyHGST,iv:c4Ivmm9TEGoPt4QPmRQzcTaXvfdtRSYVpjU6dGgdPhQ=,tag:Xn4zW2E4ZjpQGBYHxrmO+Q==,type:str]
            - ENC[AES256_GCM,data:aDLhg3+T+tS1oGLExy9IeiCpoOpAk13GjS5iMykKTOTQ2uewwaI6tMivTIpmKw8vzE35iXO2TIiP/Q==,iv:tw9oCZ/MXu0xMRxNwnwKjjRg/ID1ZUdu+Zh0960BOvg=,tag:padbKbLIrw90Kle2qGKy1w==,type:str]
            - ENC[AES256_GCM,data:kqPHV86HvKcLqQrjqvh/jK220O+ewDXy1LAFgfC98rQjmL4Bg11ApqYGdalIKv7dta1YWGXNGg==,iv:AzArOtA15WxxBLtAQ9PdOn/4gQG0Wokf7av3vgNG9nU=,tag:lDQbHCl32N3JL+uF+mtfZA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzdrwhr2s5rcgp50kwk29kmtmqamrd66tst8fly6hnq0y4yq395smdz4yn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5VmNUQldQaUxNc1k2VDhY
            Yk1GaHZVUmtST1U4alBLWlpPb1dteEpXV240CmVoVjlWSGl2Q0w2ZEhKL3Uyb3Fw
            N2lKV0xDa05xOTU5OEp0ZUZhWnlncGMKLS0tIENSUEVNaVhYcjl6azNaTEtrQk9J
            ZFZJaERSY3J0ckV0SkM0d0JMb2Q5cWcKWo/cJ174w1OWfGAKaLok0TPfeW6UWdeR
            DDYo8D85BUIIcavB2vnQIHlWJdQrmOmYXJRCqMuyBB9PrfBPCkMiLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cu0zpj3jphz2gxzqnqx9qq43ppkv9ujj2gtmp8lsge075xrcjdeqe8u4r6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3aStmcnBIR2hsVkgzUWdB
            cU02dGdUY3lnR0ZjK01yWHNNWnRtREhxdUFZCm82KytLdWp2N0ZXbTRnaFRFbG9F
            SmVlZU5lYXo2QkFqOTFtZFNuYmtySlkKLS0tIG8rSmFSendQNkV2Qm5GWHVXM0hK
            amtFbE10LzAvSVgzVEtHMFd6Z1pnV1EKYTbvfeZRgAC3yOEW4ldDuWjG2wl0REP3
            joYTcGQ3PJrTphw99SXKbbKrhiAqUUXis9OXTPWtNEnnZsxZv95lRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-27T00:06:16Z"
    mac: ENC[AES256_GCM,data:q6K46+PuQCbWiZ9TUVCLHJMcDVmo0x/6FKu/ScLKHZIDwEhZVCWgELebUzf/sraqwfDmafMk//5OJDpnHjExRVUaqrrRIKeUxSbBcAMrcixhS7jA6frBFRDU3/U1z71ggDoV0dezBMCRyz2R0dw7UH0oT2uXc/Zpsluf6nyfCy0=,iv:g+ge9RImeem6cYYK/VT4PJNtWtGdoW+R9/PInbmA3aE=,tag:YqYhYBghkl6ORx9nvueJWw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
