home-assistant:
    ingress:
        main:
            annotations:
                external-dns.alpha.kubernetes.io/target: ENC[AES256_GCM,data:dLWQ3JKzgfV0cqq0c1o=,iv:BHwwytdbtSkyUeRBP42G5Psbi+W7xD7jBrwODvInmJc=,tag:QzcBPoZ6nvxW9LGRyX9Y1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzdrwhr2s5rcgp50kwk29kmtmqamrd66tst8fly6hnq0y4yq395smdz4yn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTXMweW43azJZbmdCWkdS
            QnAzZVY1NEZRRXBGdWZyYnlDamxxS0NHTERzCmc3SnVDODhsTUd0cmRZVEpkdzlW
            cEMwZUI4MVVYYkVCeHVFSlp4cTFZb2sKLS0tIEh4Z05MMU14YmRkWUt5bGRnNHk2
            OU4wVHJzcFFLSGxrSDZtajNyRTR3TnMK2X6kHUBX7snlNCVW88qpOgzMcIxXBzBL
            1I84Y5G4hsUvD94tD+E3YN1eF4w3Yd0dWsUD2ctyaXxNTZgpu02aFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-19T11:58:18Z"
    mac: ENC[AES256_GCM,data:fo5lIAT1ljRRyJgeaUuFpkdTeucURQfhcCWQ10FVkRNvkCEin1KXZlV33IuWYSTH+nuPDp4U121nDR42Gx6IZv/fAaHzyjwNQ0LB189HTKtnAfZqtks8VzRdgwoJtYI8wU/xSkJM/+gdU1cPi/oGOlTwM/vgBA+HCiZaHee/7vA=,iv:ynWEK2wlqDR7pPBNMMrhiHw/1v3vnCSuhytrUrG4E/g=,tag:OSRDCume1uwemgCHkV3GTw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
