external-dns:
    env:
        - name: ENC[AES256_GCM,data:f3m3HFdg21GtMA==,iv:xZ3ocvzw4rcLGqeQyL8Sfq4Y+OTkkb+i1ztz660nO5c=,tag:5tPnJbuAhWfTEHFgaqLa8A==,type:str]
          value: ENC[AES256_GCM,data:VcNbrGsMQaeIB/mip49cCSO5tgE=,iv:eatehlxzYpnHYkaFS1CQR4Ak81ILHmeEEMif9/8do8E=,tag:tkoCba5KFHaxMIhPwMXNFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kzdrwhr2s5rcgp50kwk29kmtmqamrd66tst8fly6hnq0y4yq395smdz4yn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWamRjZEZqNWs4TzFNY3ZP
            L0FZWWtwN3R1bWpCb0N4MFZOOWh3UTNQN1ZvCnYzYjdMT0RCU2JUM3FzY08yV0Jz
            TmZLWkN3M0FEa2R3RTlEdlNVNVQ2K0EKLS0tIFdiK1FmbThxaklacVd1OFBoSW9R
            SHRRelNFaGV6TXdibjNYdjdyWmhzTmsK+3DV5yggrEX9OgbnXZJp7kn6OgVl/H3C
            UGeveUA+tIZWSO9ua1/iCUCgRC5FMU39u6vqtJqbfob6eL7U7RFKMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-17T01:28:16Z"
    mac: ENC[AES256_GCM,data:4y8rOuCMuEr+CGQ2fjiTjSmBMADCAhnBMGXveL+oR7SxveXRKcFfyHG1yxIUtfMh42/5v7LATjO45lOePZGXmkDG8lR0gVYHlP2AtDxg7/cO4EN6iwcyGv18EdZiM4aOBRAPK5hQRE0QuBTv7AgU9KYsRHWOOtP2dad+VO7ojkk=,iv:I0WuyqMSxDLppD5Z1YRcGLMBjUT8mGdarLi28KgIIqw=,tag:ZlY6ojvDSjxoosF2w+EgSQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
